library:
  source-dirs: src
  ghc-options:
  - -Wall
tests:
  mlem-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - mlem
copyright: 2018 Author name here
maintainer: root@gws.fyi
dependencies:
- mtl
- constraints
- base >= 4.7 && < 5
- lens
- classy-prelude
- constraints
default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- GADTSyntax
- TypeFamilies
- FlexibleInstances
- FlexibleContexts
- FunctionalDependencies
- DataKinds
- PolyKinds
- TypeOperators
- TypeApplications
- ScopedTypeVariables
- DerivingStrategies
- GeneralizedNewtypeDeriving
- DeriveAnyClass
- DeriveGeneric
name: mlem
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/mlem
license: BSD3
executables:
  mlem-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mlem
description: Please see the README on GitHub at <https://github.com/githubuser/mlem#readme>
description: Please see the README on GitHub at <https://github.com/githubuser/mlem#readme>
